name: Release request
description: Propose a new release
title: "[Release]: v"
labels: ["release"]
body:
  - type: input
    id: version
    attributes:
      label: Version
      placeholder: v1.2.3
    validations:
      required: true
  - type: textarea
    id: highlights
    attributes:
      label: Highlights
      description: What's new in this release?
    validations:
      required: true
  - type: textarea
    id: risks
    attributes:
      label: Risks / rollback plan
